package ws.msg.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-19T14:02:14.340+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "BEWG_Message_ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BEWGMessageServiceSoap {

    @WebMethod(operationName = "RefreshCache", action = "http://tempuri.org/RefreshCache")
    @RequestWrapper(localName = "RefreshCache", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.RefreshCache")
    @ResponseWrapper(localName = "RefreshCacheResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.RefreshCacheResponse")
    @WebResult(name = "RefreshCacheResult", targetNamespace = "http://tempuri.org/")
    public MessageBack refreshCache(
            @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
                    String token
    );

    @WebMethod(operationName = "SendDT_Link", action = "http://tempuri.org/SendDT_Link")
    @RequestWrapper(localName = "SendDT_Link", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendDTLink")
    @ResponseWrapper(localName = "SendDT_LinkResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendDTLinkResponse")
    @WebResult(name = "SendDT_LinkResult", targetNamespace = "http://tempuri.org/")
    public MessageBack sendDTLink(
            @WebParam(name = "link_message", targetNamespace = "http://tempuri.org/")
                    MessageDTLink linkMessage
    );

    @WebMethod(operationName = "HandleEmailServer", action = "http://tempuri.org/HandleEmailServer")
    @RequestWrapper(localName = "HandleEmailServer", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.HandleEmailServer")
    @ResponseWrapper(localName = "HandleEmailServerResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.HandleEmailServerResponse")
    @WebResult(name = "HandleEmailServerResult", targetNamespace = "http://tempuri.org/")
    public MessageBack handleEmailServer(
            @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
                    String email,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password
    );

    @WebMethod(operationName = "SendDT", action = "http://tempuri.org/SendDT")
    @RequestWrapper(localName = "SendDT", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendDT")
    @ResponseWrapper(localName = "SendDTResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendDTResponse")
    @WebResult(name = "SendDTResult", targetNamespace = "http://tempuri.org/")
    public MessageBack sendDT(
            @WebParam(name = "message", targetNamespace = "http://tempuri.org/")
                    MessageDT message
    );

    @WebMethod(operationName = "GetSmsStatus", action = "http://tempuri.org/GetSmsStatus")
    @RequestWrapper(localName = "GetSmsStatus", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.GetSmsStatus")
    @ResponseWrapper(localName = "GetSmsStatusResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.GetSmsStatusResponse")
    @WebResult(name = "GetSmsStatusResult", targetNamespace = "http://tempuri.org/")
    public MessageStatus getSmsStatus(
            @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
                    String code
    );

    @WebMethod(operationName = "SendWx_Text", action = "http://tempuri.org/SendWx_Text")
    @RequestWrapper(localName = "SendWx_Text", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendWxText")
    @ResponseWrapper(localName = "SendWx_TextResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendWxTextResponse")
    @WebResult(name = "SendWx_TextResult", targetNamespace = "http://tempuri.org/")
    public MessageBack sendWxText(
            @WebParam(name = "text_message", targetNamespace = "http://tempuri.org/")
                    MessageWxText textMessage
    );

    @WebMethod(operationName = "GetEmailStatus", action = "http://tempuri.org/GetEmailStatus")
    @RequestWrapper(localName = "GetEmailStatus", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.GetEmailStatus")
    @ResponseWrapper(localName = "GetEmailStatusResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.GetEmailStatusResponse")
    @WebResult(name = "GetEmailStatusResult", targetNamespace = "http://tempuri.org/")
    public MessageStatus getEmailStatus(
            @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
                    String code
    );

    @WebMethod(operationName = "GetDtStatus", action = "http://tempuri.org/GetDtStatus")
    @RequestWrapper(localName = "GetDtStatus", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.GetDtStatus")
    @ResponseWrapper(localName = "GetDtStatusResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.GetDtStatusResponse")
    @WebResult(name = "GetDtStatusResult", targetNamespace = "http://tempuri.org/")
    public MessageStatus getDtStatus(
            @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
                    String code
    );

    @WebMethod(operationName = "GetWxStatus", action = "http://tempuri.org/GetWxStatus")
    @RequestWrapper(localName = "GetWxStatus", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.GetWxStatus")
    @ResponseWrapper(localName = "GetWxStatusResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.GetWxStatusResponse")
    @WebResult(name = "GetWxStatusResult", targetNamespace = "http://tempuri.org/")
    public MessageStatus getWxStatus(
            @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
                    String code
    );

    @WebMethod(operationName = "SendSMS_Template", action = "http://tempuri.org/SendSMS_Template")
    @RequestWrapper(localName = "SendSMS_Template", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendSMSTemplate")
    @ResponseWrapper(localName = "SendSMS_TemplateResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendSMSTemplateResponse")
    @WebResult(name = "SendSMS_TemplateResult", targetNamespace = "http://tempuri.org/")
    public MessageBack sendSMSTemplate(
            @WebParam(name = "template", targetNamespace = "http://tempuri.org/")
                    MessageSMSTemplate template
    );

    @WebMethod(operationName = "SendSMS", action = "http://tempuri.org/SendSMS")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendSMSResponse")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://tempuri.org/")
    public MessageBack sendSMS(
            @WebParam(name = "message", targetNamespace = "http://tempuri.org/")
                    MessageSMS message
    );

    @WebMethod(operationName = "SendDT_Text", action = "http://tempuri.org/SendDT_Text")
    @RequestWrapper(localName = "SendDT_Text", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendDTText")
    @ResponseWrapper(localName = "SendDT_TextResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendDTTextResponse")
    @WebResult(name = "SendDT_TextResult", targetNamespace = "http://tempuri.org/")
    public MessageBack sendDTText(
            @WebParam(name = "text_message", targetNamespace = "http://tempuri.org/")
                    MessageDTText textMessage
    );

    @WebMethod(operationName = "SendWx_News", action = "http://tempuri.org/SendWx_News")
    @RequestWrapper(localName = "SendWx_News", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendWxNews")
    @ResponseWrapper(localName = "SendWx_NewsResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendWxNewsResponse")
    @WebResult(name = "SendWx_NewsResult", targetNamespace = "http://tempuri.org/")
    public MessageBack sendWxNews(
            @WebParam(name = "news_message", targetNamespace = "http://tempuri.org/")
                    MessageWxNews newsMessage
    );

    @WebMethod(operationName = "SendWx", action = "http://tempuri.org/SendWx")
    @RequestWrapper(localName = "SendWx", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendWx")
    @ResponseWrapper(localName = "SendWxResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendWxResponse")
    @WebResult(name = "SendWxResult", targetNamespace = "http://tempuri.org/")
    public MessageBack sendWx(
            @WebParam(name = "message", targetNamespace = "http://tempuri.org/")
                    MessageWx message
    );

    @WebMethod(operationName = "SendEmail", action = "http://tempuri.org/SendEmail")
    @RequestWrapper(localName = "SendEmail", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendEmail")
    @ResponseWrapper(localName = "SendEmailResponse", targetNamespace = "http://tempuri.org/", className = "ws.msg.client.SendEmailResponse")
    @WebResult(name = "SendEmailResult", targetNamespace = "http://tempuri.org/")
    public MessageBack sendEmail(
            @WebParam(name = "message", targetNamespace = "http://tempuri.org/")
                    MessageEmail message
    );
}
