package ws.msg.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-17T17:32:03.807+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "BEWG_Message_ServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BEWGMessageServiceHttpPost {

    @WebMethod(operationName = "GetSmsStatus")
    @WebResult(name = "MessageStatus", targetNamespace = "http://tempuri.org/", partName = "Body")
    public MessageStatus getSmsStatus(
            @WebParam(partName = "id", name = "id", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(partName = "code", name = "code", targetNamespace = "http://tempuri.org/")
                    String code
    );

    @WebMethod(operationName = "GetEmailStatus")
    @WebResult(name = "MessageStatus", targetNamespace = "http://tempuri.org/", partName = "Body")
    public MessageStatus getEmailStatus(
            @WebParam(partName = "id", name = "id", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(partName = "code", name = "code", targetNamespace = "http://tempuri.org/")
                    String code
    );

    @WebMethod(operationName = "RefreshCache")
    @WebResult(name = "MessageBack", targetNamespace = "http://tempuri.org/", partName = "Body")
    public MessageBack refreshCache(
            @WebParam(partName = "token", name = "token", targetNamespace = "http://tempuri.org/")
                    String token
    );

    @WebMethod(operationName = "GetDtStatus")
    @WebResult(name = "MessageStatus", targetNamespace = "http://tempuri.org/", partName = "Body")
    public MessageStatus getDtStatus(
            @WebParam(partName = "id", name = "id", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(partName = "code", name = "code", targetNamespace = "http://tempuri.org/")
                    String code
    );

    @WebMethod(operationName = "GetWxStatus")
    @WebResult(name = "MessageStatus", targetNamespace = "http://tempuri.org/", partName = "Body")
    public MessageStatus getWxStatus(
            @WebParam(partName = "id", name = "id", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(partName = "code", name = "code", targetNamespace = "http://tempuri.org/")
                    String code
    );

    @WebMethod(operationName = "HandleEmailServer")
    @WebResult(name = "MessageBack", targetNamespace = "http://tempuri.org/", partName = "Body")
    public MessageBack handleEmailServer(
            @WebParam(partName = "email", name = "email", targetNamespace = "http://tempuri.org/")
                    String email,
            @WebParam(partName = "password", name = "password", targetNamespace = "http://tempuri.org/")
                    String password
    );
}
