package com.yk.rcm.ws.client.contract;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.12
 * 2017-04-26T19:31:28.158+08:00
 * Generated source version: 3.0.12
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ReceiveInvestmentItemsSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ReceiveInvestmentItemsSoap {

    @WebResult(name = "GetInvestmentItemsMessageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInvestmentItemsMessage", targetNamespace = "http://tempuri.org/", className = "com.yk.rcm.ws.client.contract.GetInvestmentItemsMessage")
    @WebMethod(operationName = "GetInvestmentItemsMessage", action = "http://tempuri.org/GetInvestmentItemsMessage")
    @ResponseWrapper(localName = "GetInvestmentItemsMessageResponse", targetNamespace = "http://tempuri.org/", className = "com.yk.rcm.ws.client.contract.GetInvestmentItemsMessageResponse")
    public java.lang.String getInvestmentItemsMessage(
        @WebParam(name = "requestJsonStr", targetNamespace = "http://tempuri.org/")
        java.lang.String requestJsonStr
    );
}
