package com.yk.rcm.ws.client.contract;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import util.PropertiesUtil;

/**
 * This class was generated by Apache CXF 3.0.12
 * 2017-04-26T19:31:28.199+08:00
 * Generated source version: 3.0.12
 * 
 */
@WebServiceClient(name = "ReceiveInvestmentItems", 
                  wsdlLocation = "http://10.10.2.49/ContractInterface/asmx/ReceiveInvestmentItems.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class ReceiveInvestmentItems extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ReceiveInvestmentItems");
    public final static QName ReceiveInvestmentItemsSoap = new QName("http://tempuri.org/", "ReceiveInvestmentItemsSoap");
    public final static QName ReceiveInvestmentItemsSoap12 = new QName("http://tempuri.org/", "ReceiveInvestmentItemsSoap12");
    public final static QName ReceiveInvestmentItemsHttpPost = new QName("http://tempuri.org/", "ReceiveInvestmentItemsHttpPost");
    public final static QName ReceiveInvestmentItemsHttpGet = new QName("http://tempuri.org/", "ReceiveInvestmentItemsHttpGet");
    static {
        URL url = null;
        String clientUrl = PropertiesUtil.getProperty("ws_ht_send_addr");
        try {
            url = new URL(clientUrl);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReceiveInvestmentItems.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", clientUrl);
        }
        WSDL_LOCATION = url;
    }

    public ReceiveInvestmentItems(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReceiveInvestmentItems(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceiveInvestmentItems() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ReceiveInvestmentItemsSoap
     */
    @WebEndpoint(name = "ReceiveInvestmentItemsSoap")
    public ReceiveInvestmentItemsSoap getReceiveInvestmentItemsSoap() {
        return super.getPort(ReceiveInvestmentItemsSoap, ReceiveInvestmentItemsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveInvestmentItemsSoap
     */
    @WebEndpoint(name = "ReceiveInvestmentItemsSoap")
    public ReceiveInvestmentItemsSoap getReceiveInvestmentItemsSoap(WebServiceFeature... features) {
        return super.getPort(ReceiveInvestmentItemsSoap, ReceiveInvestmentItemsSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ReceiveInvestmentItemsSoap
     */
    @WebEndpoint(name = "ReceiveInvestmentItemsSoap12")
    public ReceiveInvestmentItemsSoap getReceiveInvestmentItemsSoap12() {
        return super.getPort(ReceiveInvestmentItemsSoap12, ReceiveInvestmentItemsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveInvestmentItemsSoap
     */
    @WebEndpoint(name = "ReceiveInvestmentItemsSoap12")
    public ReceiveInvestmentItemsSoap getReceiveInvestmentItemsSoap12(WebServiceFeature... features) {
        return super.getPort(ReceiveInvestmentItemsSoap12, ReceiveInvestmentItemsSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ReceiveInvestmentItemsHttpPost
     */
    @WebEndpoint(name = "ReceiveInvestmentItemsHttpPost")
    public ReceiveInvestmentItemsHttpPost getReceiveInvestmentItemsHttpPost() {
        return super.getPort(ReceiveInvestmentItemsHttpPost, ReceiveInvestmentItemsHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveInvestmentItemsHttpPost
     */
    @WebEndpoint(name = "ReceiveInvestmentItemsHttpPost")
    public ReceiveInvestmentItemsHttpPost getReceiveInvestmentItemsHttpPost(WebServiceFeature... features) {
        return super.getPort(ReceiveInvestmentItemsHttpPost, ReceiveInvestmentItemsHttpPost.class, features);
    }
    /**
     *
     * @return
     *     returns ReceiveInvestmentItemsHttpGet
     */
    @WebEndpoint(name = "ReceiveInvestmentItemsHttpGet")
    public ReceiveInvestmentItemsHttpGet getReceiveInvestmentItemsHttpGet() {
        return super.getPort(ReceiveInvestmentItemsHttpGet, ReceiveInvestmentItemsHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveInvestmentItemsHttpGet
     */
    @WebEndpoint(name = "ReceiveInvestmentItemsHttpGet")
    public ReceiveInvestmentItemsHttpGet getReceiveInvestmentItemsHttpGet(WebServiceFeature... features) {
        return super.getPort(ReceiveInvestmentItemsHttpGet, ReceiveInvestmentItemsHttpGet.class, features);
    }

}
