
package com.yk.rcm.ws.client.tz;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.12
 * 2017-04-26T19:10:19.250+08:00
 * Generated source version: 3.0.12
 * 
 */
public final class RiskServiceSoap_RiskServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "RiskService");

    private RiskServiceSoap_RiskServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RiskService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RiskService ss = new RiskService(wsdlURL, SERVICE_NAME);
        RiskServiceSoap port = ss.getRiskServiceSoap12();  
        
        {
        System.out.println("Invoking helloWorld...");
        java.lang.String _helloWorld__return = port.helloWorld();
        System.out.println("helloWorld.result=" + _helloWorld__return);


        }
        {
        System.out.println("Invoking synchronous...");
        java.lang.String _synchronous__return = port.synchronous();
        System.out.println("synchronous.result=" + _synchronous__return);


        }
        {
        System.out.println("Invoking updateRiskAuditInfo...");
        java.lang.String _updateRiskAuditInfo_customerId = "";
        java.lang.String _updateRiskAuditInfo_riskStatus = "";
        java.lang.String _updateRiskAuditInfo_auditReport = "";
        java.lang.String _updateRiskAuditInfo__return = port.updateRiskAuditInfo(_updateRiskAuditInfo_customerId, _updateRiskAuditInfo_riskStatus, _updateRiskAuditInfo_auditReport);
        System.out.println("updateRiskAuditInfo.result=" + _updateRiskAuditInfo__return);


        }

        System.exit(0);
    }

}
