
package ws.client.portal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUpToDoService", targetNamespace = "http://service.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUpToDoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "todoList", targetNamespace = "http://service.ws.com/", className = "ws.client.portal.TodoList")
    @ResponseWrapper(localName = "todoListResponse", targetNamespace = "http://service.ws.com/", className = "ws.client.portal.TodoListResponse")
    public String todoList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
