
package ws.client.message;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BEWG_Message_Service", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.10.20.82:8080/message/service?wsdl")
public class BEWGMessageService
    extends Service
{

    private final static URL BEWGMESSAGESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ws.client.message.BEWGMessageService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ws.client.message.BEWGMessageService.class.getResource(".");
            url = new URL(baseUrl, "http://10.10.20.82:8080/message/service?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.10.20.82:8080/message/service?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BEWGMESSAGESERVICE_WSDL_LOCATION = url;
    }

    public BEWGMessageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BEWGMessageService() {
        super(BEWGMESSAGESERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "BEWG_Message_Service"));
    }

    /**
     * 
     * @return
     *     returns BEWGMessageServiceSoap
     */
    @WebEndpoint(name = "BEWG_Message_ServiceSoap")
    public BEWGMessageServiceSoap getBEWGMessageServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "BEWG_Message_ServiceSoap"), BEWGMessageServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BEWGMessageServiceSoap
     */
    @WebEndpoint(name = "BEWG_Message_ServiceSoap")
    public BEWGMessageServiceSoap getBEWGMessageServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BEWG_Message_ServiceSoap"), BEWGMessageServiceSoap.class, features);
    }

}
